project_id       = "gke-prod-demo-001"
region           = "asia-south1"
zone             = "asia-south1-a"
cluster_name     = "prod-gke-cluster"
argocd_namespace = "argocd"
gitops_repo_url  = "https://github.com/linuxshakil/gke-argocd-gitops.git"
