environment: dev

image:
  repository: asia-south1-docker.pkg.dev/gke-prod-demo-001/demo-app/demo-app
  tag: "latest"
  pullPolicy: IfNotPresent

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 70

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: false
  host: ""
  className: "gce"

serviceAccount:
  create: true
  name: ""

podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}
