environment: test

preSyncCheck:
  enabled: true

image:
  tag: "sha-03fc701"

replicaCount: 2

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 250m
    memory: 256Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 70

ingress:
  enabled: true
  host: "test.myahad.online"
  className: "gce"
