environment: prod

preSyncCheck:
  enabled: true

rollout:
  enabled: true
  steps:
    - setWeight: 20
    - pause: { duration: 60 }
    - setWeight: 50
    - pause: { duration: 120 }
    - setWeight: 100

image:
  tag: "v1.0.0"
  digest: "sha256:48511351b9a93ebc33a5e02ba3b6fb9d2e58aef995167c80230b48203d236b36"

replicaCount: 3

resources:
  requests:
    cpu: 250m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 60

ingress:
  enabled: true
  host: "prod.myahad.online"
  className: "gce"

podAnnotations:
  "prometheus.io/scrape": "true"
  "prometheus.io/port": "8080"
